name: Continuous Integration tests

on:
  pull_request:
  push:

jobs:
  ci_tests:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::452750982249:role/service-role/eagle-GitHub-test-role
          role-session-name: github-ci-tests
          aws-region: us-west-2

      - uses: actions/checkout@v3
      # run all test cases
      - name: Run S3EC Test Cases
        run: |
          export AWS_S3EC_TEST_BUCKET=eagle-github-test-bucket
          export AWS_S3EC_TEST_KMS_KEY_ID=arn:aws:kms:us-west-2:452750982249:key/d175b216-d2b0-40db-a8eb-5eda6601fe17
          export AWS_S3EC_TEST_KMS_KEY_ALIAS=arn:aws:kms:us-west-2:452750982249:alias/eagle-Github-KMS-Key
          export AWS_REGION=us-west-2
          mvn -B -ntp test